<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '24/7 Поддержка' => '',
    'Web Club' => '',
    'Войти' => '',
    'Войти / Зарегистрироватся' => '',
    'Вопросы и ответы' => '',
    'Восстановить' => '',
    'Все курсы' => '',
    'Все лайфхаки' => '',
    'Выйти' => '',
    'Главная' => '',
    'Главная страница' => '',
    'Год открытия' => '',
    'Задании по данному уроку были завершены. Вы набрали {ball} баллов' => '',
    'Запомни меня' => '',
    'Зарегистрированных учеников' => '',
    'Зарегистрироватся' => '',
    'Зарегистрируйтесь и пройдите наши бесплатные курсы' => '',
    'Изучайте Web разработку вместе с нами' => '',
    'Информация' => '',
    'Количество курсов' => '',
    'Контакты' => '',
    'Курс' => '',
    'Курсы' => '',
    'Лайфхак' => '',
    'Лайфхаки' => '',
    'Мобильное приложение' => '',
    'Мои курсы' => '',
    'Мой профиль' => '',
    'Наши курсы' => '',
    'Неправильный логин или пароль' => '',
    'О нас' => '',
    'Онлайн курсы' => '',
    'Онлайн тестирование' => '',
    'Отправить' => '',
    'Пароли не совпадают' => '',
    'Пароль' => '',
    'Пароль должен содержать минимум 6 символов' => '',
    'Пароль должен содержать только латинские буквы, спецсимволы и/или цифры' => '',
    'Подробнее' => '',
    'Посмотреть все курсы' => '',
    'Привет' => '',
    'Придумайте пароль' => '',
    'Приложения' => '',
    'Приобрести' => '',
    'Публичная оферта' => '',
    'Сертификат' => '',
    'Сохранить' => '',
    'ТОП 100' => '',
    'Тестирования' => '',
    'Увы... У вас нет ни одного курсы' => '',
    'Чтобы авторизоватся заполните форму ниже' => '',
];
